/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Amlogic Meson6/8/8b/8m2 secure TrustZone firmware definitions.
 *
 * Based on meson-secure.c and meson-secure.h from the Amlogic vendor kernel:
 *   Copyright (C) 2002 ARM Ltd.
 *   Copyright (c) 2010, Code Aurora Forum. All rights reserved.
 *   Copyright (C) 2013 Amlogic, Inc.
 *     Author: Platform-SH@amlogic.com
 *
 * Copyright (C) 2021 Martin Blumenstingl <martin.blumenstingl@googlemail.com>
 */

/* Meson Secure Monitor/HAL APIs */
#define MESON_CALL_TRUSTZONE_API			0x1
#define MESON_CALL_TRUSTZONE_MON			0x4
#define MESON_CALL_TRUSTZONE_HAL_API			0x5

/* Secure Monitor mode APIs */
#define MESON_TRUSTZONE_MON_TYPE_MASK			0xF00
#define MESON_TRUSTZONE_MON_FUNC_MASK			0x0FF

#define MESON_TRUSTZONE_MON_L2X0			0x100
#define MESON_TRUSTZONE_MON_L2X0_CTRL_INDEX		0x101
#define MESON_TRUSTZONE_MON_L2X0_AUXCTRL_INDEX		0x102
#define MESON_TRUSTZONE_MON_L2X0_PREFETCH_INDEX		0x103
#define MESON_TRUSTZONE_MON_L2X0_TAGLATENCY_INDEX	0x104
#define MESON_TRUSTZONE_MON_L2X0_DATALATENCY_INDEX	0x105
#define MESON_TRUSTZONE_MON_L2X0_FILTERSTART_INDEX	0x106
#define MESON_TRUSTZONE_MON_L2X0_FILTEREND_INDEX	0x107
#define MESON_TRUSTZONE_MON_L2X0_DEBUG_INDEX		0x108
#define MESON_TRUSTZONE_MON_L2X0_POWER_INDEX		0x109

#define MESON_TRUSTZONE_MON_CORE			0x200
#define MESON_TRUSTZONE_MON_CORE_RD_CTRL_INDEX		0x201
#define MESON_TRUSTZONE_MON_CORE_WR_CTRL_INDEX		0x202
#define MESON_TRUSTZONE_MON_CORE_RD_STATUS0_INDEX	0x203
#define MESON_TRUSTZONE_MON_CORE_WR_STATUS0_INDEX	0x204
#define MESON_TRUSTZONE_MON_CORE_RD_STATUS1_INDEX	0x205
#define MESON_TRUSTZONE_MON_CORE_WR_STATUS1_INDEX	0x206
#define MESON_TRUSTZONE_MON_CORE_BOOTADDR_INDEX		0x207
#define MESON_TRUSTZONE_MON_CORE_DDR_INDEX		0x208
#define MESON_TRUSTZONE_MON_CORE_RD_SOC_REV1		0x209
#define MESON_TRUSTZONE_MON_CORE_RD_SOC_REV2		0x20A

#define MESON_TRUSTZONE_MON_SUSPEND_FIRMWARE		0x300
#define MESON_TRUSTZONE_MON_SAVE_CPU_GIC		0x400

#define MESON_TRUSTZONE_MON_RTC				0x500
#define MESON_TRUSTZONE_MON_RTC_RD_REG_INDEX		0x501
#define MESON_TRUSTZONE_MON_RTC_WR_REG_INDEX		0x502

#define MESON_TRUSTZONE_MON_REG				0x600
#define MESON_TRUSTZONE_MON_REG_RD_INDEX		0x601
#define MESON_TRUSTZONE_MON_REG_WR_INDEX		0x602

#define MESON_TRUSTZONE_MON_MEM				0x700
#define MESON_TRUSTZONE_MON_MEM_BASE			0x701
#define MESON_TRUSTZONE_MON_MEM_TOTAL_SIZE		0x702
#define MESON_TRUSTZONE_MON_MEM_FLASH			0x703
#define MESON_TRUSTZONE_MON_MEM_FLASH_SIZE		0x704
#define MESON_TRUSTZONE_MON_MEM_GE2D			0x705

/* Secure HAL APIs*/
#define MESON_TRUSTZONE_HAL_API_EFUSE			0x100
#define MESON_TRUSTZONE_HAL_API_EFUSE_CMD_READ		0x0
#define MESON_TRUSTZONE_HAL_API_EFUSE_CMD_WRITE		0x1
#define MESON_TRUSTZONE_HAL_API_EFUSE_CMD_VERIFY_IMG	0x3

#define MESON_TRUSTZONE_HAL_API_STORAGE			0x200

#define MESON_TRUSTZONE_HAL_API_MEMCONFIG		0x300
#define MESON_TRUSTZONE_HAL_API_MEMCONFIG_GE2D		0x301

void __init meson_mx_trustzone_firmware_init(void);
void __init meson_mx_trustzone_firmware_reserve_mem(void);
