// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) 2020 Martin Blumenstingl <martin.blumenstingl@googlemail.com>
 *
 * All registers and magic values are taken from Amlogic's GPL kernel sources:
 *   Copyright (C) 2010 Amlogic, Inc.
 */

#include <linux/bitfield.h>
#include <linux/bits.h>

#ifndef __TXCCQ_TXC_84352_H__
#define __TXCCQ_TXC_84352_H__

/* HDMI TX register */

// System config 0
#define TX_SYS0_AFE_SIGNAL						0x0000
#define TX_SYS0_AFE_LOOP						0x0001
#define TX_SYS0_ACR_CTS_0						0x0002
	#define TX_SYS0_ACR_CTS_0_AUDIO_CTS_BYTE0		GENMASK(7, 0)
#define TX_SYS0_ACR_CTS_1						0x0003
	#define TX_SYS0_ACR_CTS_1_AUDIO_CTS_BYTE1		GENMASK(7, 0)
#define TX_SYS0_ACR_CTS_2						0x0004
	#define TX_SYS0_ACR_CTS_2_FORCE_ARC_STABLE			BIT(5)
#define TX_SYS0_BIST_CONTROL						0x0005
	#define TX_SYS0_BIST_CONTROL_AFE_BIST_ENABLE			BIT(7)
	#define TX_SYS0_BIST_CONTROL_TMDS_SHIFT_PATTERN_SELECT		BIT(6)
	#define TX_SYS0_BIST_CONTROL_TMDS_PRBS_PATTERN_SELECT	GENMASK(5, 4)
	#define TX_SYS0_BIST_CONTROL_TMDS_REPEAT_BIST_PATTERN	GENMASK(2, 0)

#define TX_SYS0_BIST_DATA_0						0x0006
#define TX_SYS0_BIST_DATA_1						0x0007
#define TX_SYS0_BIST_DATA_2						0x0008
#define TX_SYS0_BIST_DATA_3						0x0009
#define TX_SYS0_BIST_DATA_4						0x000A
#define TX_SYS0_BIST_DATA_5						0x000B
#define TX_SYS0_BIST_DATA_6						0x000C
#define TX_SYS0_BIST_DATA_7						0x000D
#define TX_SYS0_BIST_DATA_8						0x000E
#define TX_SYS0_BIST_DATA_9						0x000F

#define TX_SYS1_ACR_N_0							0x001C
	#define TX_SYS1_ACR_N_0_N_BYTE0				GENMASK(7, 0)
#define TX_SYS1_ACR_N_1							0x001D
	#define TX_SYS1_ACR_N_1_N_BYTE1				GENMASK(7, 0)
#define TX_SYS1_ACR_N_2							0x001E
	#define TX_SYS1_ACR_N_2_N_MEAS_TOLERANCE		GENMASK(7, 4)
	#define TX_SYS1_ACR_N_2_N_UPPER_NIBBLE			GENMASK(3, 0)
#define TX_SYS1_PRBS_DATA						0x001F
	#define TX_SYS1_PRBS_DATA_PRBS_MODE			GENMASK(1, 0)
	#define TX_SYS1_PRBS_DATA_PRBS_MODE_11				0x0
	#define TX_SYS1_PRBS_DATA_PRBS_MODE_15				0x1
	#define TX_SYS1_PRBS_DATA_PRBS_MODE_7				0x2
	#define TX_SYS1_PRBS_DATA_PRBS_MODE_31				0x3

// HDCP CONFIG
#define TX_HDCP_ECC_CONFIG						0x0024
#define TX_HDCP_CRC_CONFIG						0x0025
#define TX_HDCP_EDID_CONFIG						0x0026
	#define TX_HDCP_EDID_CONFIG_FORCED_SYS_TRIGGER			BIT(7)
	#define TX_HDCP_EDID_CONFIG_SYS_TRIGGER_CONFIG			BIT(6)
	#define TX_HDCP_EDID_CONFIG_MEM_ACC_SEQ_MODE			BIT(5)
	#define TX_HDCP_EDID_CONFIG_MEM_ACC_SEQ_START			BIT(4)
	#define TX_HDCP_EDID_CONFIG_FORCED_MEM_COPY_DONE		BIT(3)
	#define TX_HDCP_EDID_CONFIG_MEM_COPY_DONE_CONFIG		BIT(2)
	#define TX_HDCP_EDID_CONFIG_SYS_TRIGGER_CONFIG_SEMI_MANU	BIT(1)

#define TX_HDCP_MEM_CONFIG						0x0027
	#define TX_HDCP_MEM_CONFIG_READ_DECRYPT				BIT(3)

#define TX_HDCP_HPD_FILTER_L						0x0028
#define TX_HDCP_HPD_FILTER_H						0x0029
#define TX_HDCP_ENCRYPT_BYTE						0x002A
#define TX_HDCP_CONFIG0							0x002B
	#define TX_HDCP_CONFIG0_ROM_ENCRYPT_OFF			GENMASK(4, 3)

#define TX_HDCP_CONFIG1							0x002C
#define TX_HDCP_CONFIG2							0x002D
#define TX_HDCP_CONFIG3							0x002E
	#define TX_HDCP_CONFIG3_DDC_I2C_BUS_CLOCK_TIME_DIVIDER	GENMASK(7, 0)

#define TX_HDCP_MODE							0x002F
	#define TX_HDCP_MODE_CP_DESIRED					BIT(7)
	#define TX_HDCP_MODE_ESS_CONFIG					BIT(6)
	#define TX_HDCP_MODE_SET_AVMUTE					BIT(5)
	#define TX_HDCP_MODE_CLEAR_AVMUTE				BIT(4)
	#define TX_HDCP_MODE_HDCP_1_1					BIT(3)
	#define TX_HDCP_MODE_VSYNC_HSYNC_FORCED_POLARITY_SELECT		BIT(2)
	#define TX_HDCP_MODE_FORCED_VSYNC_POLARITY			BIT(1)
	#define TX_HDCP_MODE_FORCED_HSYNC_POLARITY			BIT(0)

// Video config, part 1
#define TX_VIDEO_ACTIVE_PIXELS_0					0x0030
#define TX_VIDEO_ACTIVE_PIXELS_1					0x0031
#define TX_VIDEO_FRONT_PIXELS						0x0032
#define TX_VIDEO_HSYNC_PIXELS						0x0033
#define TX_VIDEO_BACK_PIXELS						0x0034
#define TX_VIDEO_ACTIVE_LINES_0						0x0035
#define TX_VIDEO_ACTIVE_LINES_1						0x0036
#define TX_VIDEO_EOF_LINES						0x0037
#define TX_VIDEO_VSYNC_LINES						0x0038
#define TX_VIDEO_SOF_LINES						0x0039
#define TX_VIDEO_DTV_TIMING						0x003A
	#define TX_VIDEO_DTV_TIMING_FORCE_DTV_TIMING_AUTO		BIT(7)
	#define TX_VIDEO_DTV_TIMING_FORCE_VIDEO_SCAN			BIT(6)
	#define TX_VIDEO_DTV_TIMING_FORCE_VIDEO_FIELD			BIT(5)
	#define TX_VIDEO_DTV_TIMING_DISABLE_VIC39_CORRECTION		BIT(4)

#define TX_VIDEO_DTV_MODE						0x003B
	#define TX_VIDEO_DTV_MODE_FORCED_DEFAULT_PHASE			BIT(7)
	#define TX_VIDEO_DTV_MODE_COLOR_DEPTH			GENMASK(1, 0)

#define TX_VIDEO_DTV_FORMAT0						0x003C
#define TX_VIDEO_DTV_FORMAT1						0x003D
#define TX_VIDEO_PIXEL_PACK						0x003F
// video config, part 2
#define TX_VIDEO_CSC_COEFF_B0						0x0040
#define TX_VIDEO_CSC_COEFF_B1						0x0041
#define TX_VIDEO_CSC_COEFF_R0						0x0042
#define TX_VIDEO_CSC_COEFF_R1						0x0043
#define TX_VIDEO_CSC_COEFF_CB0						0x0044
#define TX_VIDEO_CSC_COEFF_CB1						0x0045
#define TX_VIDEO_CSC_COEFF_CR0						0x0046
#define TX_VIDEO_CSC_COEFF_CR1						0x0047
#define TX_VIDEO_DTV_OPTION_L						0x0048
	#define TX_VIDEO_DTV_OPTION_L_OUTPUT_COLOR_FORMAT	GENMASK(7, 6)
	#define TX_VIDEO_DTV_OPTION_L_INPUT_COLOR_FORMAT	GENMASK(5, 4)
	#define TX_VIDEO_DTV_OPTION_L_OUTPUT_COLOR_DEPTH	GENMASK(3, 2)
	#define TX_VIDEO_DTV_OPTION_L_INPUT_COLOR_DEPTH		GENMASK(1, 0)

#define TX_VIDEO_DTV_OPTION_H						0x0049
	#define TX_VIDEO_DTV_OPTION_H_COLOR_RANGE_16_235		0x0
	#define TX_VIDEO_DTV_OPTION_H_COLOR_RANGE_16_240		0x1
	#define TX_VIDEO_DTV_OPTION_H_COLOR_RANGE_1_254			0x2
	#define TX_VIDEO_DTV_OPTION_H_COLOR_RANGE_0_255			0x3
	#define TX_VIDEO_DTV_OPTION_H_OUTPUT_COLOR_RANGE	GENMASK(3, 2)
	#define TX_VIDEO_DTV_OPTION_H_INPUT_COLOR_RANGE		GENMASK(1, 0)

#define TX_VIDEO_DTV_FILTER						0x004A
#define TX_VIDEO_DTV_DITHER						0x004B
#define TX_VIDEO_DTV_DEDITHER						0x004C
#define TX_VIDEO_PROC_CONFIG0						0x004E
#define TX_VIDEO_PROC_CONFIG1						0x004F

// Audio config
#define TX_AUDIO_FORMAT							0x0058
	#define TX_AUDIO_FORMAT_I2S_OR_SPDIF				BIT(7)
	#define TX_AUDIO_FORMAT_I2S_2_OR_8_CH				BIT(6)
	#define TX_AUDIO_FORMAT_I2S_FORMAT			GENMASK(5, 4)
	#define TX_AUDIO_FORMAT_BIT_WIDTH			GENMASK(3, 2)
	#define TX_AUDIO_FORMAT_WS_POLARITY				BIT(1)
	#define TX_AUDIO_FORMAT_I2S_ONE_BIT_OR_I2S			BIT(0)
	#define TX_AUDIO_FORMAT_SPDIF_CHANNEL_STATUS_FROM_DATA_OR_REG	BIT(0)

#define TX_AUDIO_SPDIF							0x0059
	#define TX_AUDIO_SPDIF_ENABLE					BIT(0)
#define TX_AUDIO_I2S							0x005A
	#define TX_AUDIO_I2S_ENABLE					BIT(0)
#define TX_AUDIO_FIFO							0x005B
	#define TX_AUDIO_FIFO_FIFO_DEPTH_MASK			GENMASK(7, 4)
	#define TX_AUDIO_FIFO_FIFO_DEPTH_512				0x4
	#define TX_AUDIO_FIFO_CRITICAL_THRESHOLD_MASK		GENMASK(3, 2)
	#define TX_AUDIO_FIFO_CRITICAL_THRESHOLD_DEPTH_DIV16		0x2
	#define TX_AUDIO_FIFO_NORMAL_THRESHOLD_MASK		GENMASK(1, 0)
	#define TX_AUDIO_FIFO_NORMAL_THRESHOLD_DEPTH_DIV8		0x1
#define TX_AUDIO_LIPSYNC						0x005C
	#define TX_AUDIO_LIPSYNC_NORMALIZED_LIPSYNC_PARAM	GENMASK(7, 0)
#define TX_AUDIO_CONTROL						0x005D
	#define TX_AUDIO_CONTROL_FORCED_AUDIO_FIFO_CLEAR		BIT(7)
	#define TX_AUDIO_CONTROL_AUTO_AUDIO_FIFO_CLEAR			BIT(6)
	#define TX_AUDIO_CONTROL_AUDIO_PACKET_TYPE_MASK		GENMASK(5, 4)
	#define TX_AUDIO_CONTROL_AUDIO_PACKET_TYPE_AUDIO_SAMPLE_PACKET	0x0
	#define TX_AUDIO_CONTROL_AUDIO_PACKET_TYPE_ONE_BIT_AUDIO	0x1
	#define TX_AUDIO_CONTROL_AUDIO_PACKET_TYPE_HBR_AUDIO_PACKET	0x2
	#define TX_AUDIO_CONTROL_AUDIO_PACKET_TYPE_DST_AUDIO_PACKET	0x3
	#define TX_AUDIO_CONTROL_AUDIO_SAMPLE_PACKET_VALID		BIT(2)
	#define TX_AUDIO_CONTROL_AUDIO_SAMPLE_PACKET_USER		BIT(1)
	#define TX_AUDIO_CONTROL_AUDIO_SAMPLE_PACKET_FLAT		BIT(0)
#define TX_AUDIO_HEADER							0x005E
	#define TX_AUDIO_HEADER_AUDIO_SAMPLE_PACKET_HEADER_LAYOUT	BIT(7)
	#define TX_AUDIO_HEADER_SET_NORMAL_DOUBLE_IN_DST_PACKET_HEADER	BIT(6)
#define TX_AUDIO_SAMPLE							0x005F
	#define TX_AUDIO_SAMPLE_CHANNEL_VALID			GENMASK(7, 0)
#define TX_AUDIO_VALID							0x0060
#define TX_AUDIO_USER							0x0061
#define TX_AUDIO_PACK							0x0062
	#define TX_AUDIO_PACK_AUDIO_SAMPLE_PACKETS_ENABLE		BIT(0)
#define TX_AUDIO_CONTROL_MORE						0x0064
	#define TX_AUDIO_CONTROL_MORE_ENABLE				BIT(0)

// tmds config
#define TX_TMDS_MODE							0x0068
	#define TX_TMDS_MODE_FORCED_HDMI				BIT(7)
	#define TX_TMDS_MODE_HDMI_CONFIG				BIT(6)
	#define TX_TMDS_MODE_BIT_SWAP					BIT(3)
	#define TX_TMDS_MODE_CHANNEL_SWAP			GENMASK(2, 0)

#define TX_TMDS_CONFIG0							0x006C
#define TX_TMDS_CONFIG1							0x006D

// packet config
#define TX_PACKET_ALLOC_ACTIVE_1					0x0078
#define TX_PACKET_ALLOC_ACTIVE_2					0x0079
#define TX_PACKET_ALLOC_EOF_1						0x007A
#define TX_PACKET_ALLOC_EOF_2						0x007B
#define TX_PACKET_ALLOC_SOF_1						0x007C
#define TX_PACKET_ALLOC_SOF_2						0x007D
#define TX_PACKET_CONTROL_1						0x007E
	#define TX_PACKET_CONTROL_1_FORCE_PACKET_TIMING			BIT(7)
	#define TX_PACKET_CONTROL_1_PACKET_ALLOC_MODE			BIT(6)
	#define TX_PACKET_CONTROL_1_PACKET_START_LATENCY	GENMASK(5, 0)

#define TX_PACKET_CONTROL_2						0x007F
	#define TX_PACKET_CONTROL_2_HORIZONTAL_GC_PACKET_TRANSPORT_EN	BIT(1)

#define TX_CORE_EDID_CONFIG_MORE					0x0080
	#define TX_CORE_EDID_CONFIG_MORE_KEEP_EDID_ERROR		BIT(1)
	#define TX_CORE_EDID_CONFIG_MORE_SYS_TRIGGER_CONFIG_SEMI_MANU	BIT(0)

#define TX_CORE_ALLOC_VSYNC_0						0x0081
#define TX_CORE_ALLOC_VSYNC_1						0x0082
#define TX_CORE_ALLOC_VSYNC_2						0x0083
#define TX_MEM_PD_REG0							0x0084

// core config
#define TX_CORE_DATA_CAPTURE_1						0x00F0
#define TX_CORE_DATA_CAPTURE_2						0x00F1
	#define TX_CORE_DATA_CAPTURE_2_AUDIO_SOURCE_SELECT	GENMASK(7, 6)
	#define TX_CORE_DATA_CAPTURE_2_EXTERNAL_PACKET_ENABLE		BIT(5)
	#define TX_CORE_DATA_CAPTURE_2_INTERNAL_PACKET_ENABLE		BIT(4)
	#define TX_CORE_DATA_CAPTURE_2_AFE_FIFO_SRC_LANE1	GENMASK(3, 2)
	#define TX_CORE_DATA_CAPTURE_2_AFE_FIFO_SRC_LANE0	GENMASK(1, 0)

#define TX_CORE_DATA_MONITOR_1						0x00F2
	#define TX_CORE_DATA_MONITOR_1_LANE1				BIT(7)
	#define TX_CORE_DATA_MONITOR_1_SELECT_LANE1		GENMASK(6, 4)
	#define TX_CORE_DATA_MONITOR_1_LANE0				BIT(3)
	#define TX_CORE_DATA_MONITOR_1_SELECT_LANE0		GENMASK(2, 0)

#define TX_CORE_DATA_MONITOR_2						0x00F3
	#define TX_CORE_DATA_MONITOR_2_MONITOR_SELECT		GENMASK(2, 0)

#define TX_CORE_CALIB_MODE						0x00F4
#define TX_CORE_CALIB_SAMPLE_DELAY					0x00F5
#define TX_CORE_CALIB_VALUE_AUTO					0x00F6
#define TX_CORE_CALIB_VALUE						0x00F7

// system config 4
#define TX_SYS4_TX_CKI_DDR						0x00A0
#define TX_SYS4_TX_CKO_DDR						0x00A1
#define TX_SYS4_RX_CKI_DDR						0x00A2
#define TX_SYS4_RX_CKO_DDR						0x00A3
#define TX_SYS4_CONNECT_SEL_0						0x00A4
#define TX_SYS4_CONNECT_SEL_1						0x00A5
	#define TX_SYS4_CONNECT_SEL_1_TX_CONNECT_SEL_UPPER_CHANNEL_DATA	BIT(6)

#define TX_SYS4_CONNECT_SEL_2						0x00A6
#define TX_SYS4_CONNECT_SEL_3						0x00A7
#define TX_SYS4_CK_INV_VIDEO						0x00A8
	#define TX_SYS4_CK_INV_VIDEO_TMDS_CLK_PATTERN			BIT(4)
#define TX_SYS4_CK_INV_AUDIO						0x00A9
#define TX_SYS4_CK_INV_AFE						0x00AA
#define TX_SYS4_CK_INV_CH01						0x00AB
#define TX_SYS4_CK_INV_CH2						0x00AC
#define TX_SYS4_CK_CEC							0x00AD
#define TX_SYS4_CK_SOURCE_1						0x00AE
#define TX_SYS4_CK_SOURCE_2						0x00AF

#define TX_IEC60958_SUB1_OFFSET						0x00B0
#define TX_IEC60958_SUB2_OFFSET						0x00C8

// system config 5
#define TX_SYS5_TX_SOFT_RESET_1						0x00E0
	#define TX_SYS5_TX_SOFT_RESET_1_TX_PIXEL_RSTN			BIT(7)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_TMDS_RSTN			BIT(6)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_AUDIO_MASTER_RSTN		BIT(5)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_AUDIO_RESAMPLE_RSTN		BIT(4)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_I2S_RESET_RSTN		BIT(3)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_DIG_RESET_N_CH2		BIT(2)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_DIG_RESET_N_CH1		BIT(1)
	#define TX_SYS5_TX_SOFT_RESET_1_TX_DIG_RESET_N_CH0		BIT(0)

#define TX_SYS5_TX_SOFT_RESET_2						0x00E1
	#define TX_SYS5_TX_SOFT_RESET_2_HDMI_CH3_RST_IN			BIT(7)
	#define TX_SYS5_TX_SOFT_RESET_2_HDMI_CH2_RST_IN			BIT(6)
	#define TX_SYS5_TX_SOFT_RESET_2_HDMI_CH1_RST_IN			BIT(5)
	#define TX_SYS5_TX_SOFT_RESET_2_HDMI_CH0_RST_IN			BIT(4)
	#define TX_SYS5_TX_SOFT_RESET_2_HDMI_SR_RST			BIT(3)
	#define TX_SYS5_TX_SOFT_RESET_2_TX_DDC_HDCP_RSTN		BIT(2)
	#define TX_SYS5_TX_SOFT_RESET_2_TX_DDC_EDID_RSTN		BIT(1)
	#define TX_SYS5_TX_SOFT_RESET_2_TX_DIG_RESET_N_CH3		BIT(0)

#define TX_SYS5_RX_SOFT_RESET_1						0x00E2
#define TX_SYS5_RX_SOFT_RESET_2						0x00E3
#define TX_SYS5_RX_SOFT_RESET_3						0x00E4
#define TX_SYS5_SSTL_BIDIR_IN						0x00E5
#define TX_SYS5_SSTL_IN							0x00E6
#define TX_SYS5_SSTL_DIFF_IN						0x00E7
#define TX_SYS5_FIFO_CONFIG						0x00E8
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL2_BYPASS		BIT(6)
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL1_BYPASS		BIT(5)
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL0_BYPASS		BIT(4)
	#define TX_SYS5_FIFO_CONFIG_CLK_CHANNEL3_OUTPUT_ENABLE		BIT(3)
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL2_ENABLE		BIT(2)
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL1_ENABLE		BIT(1)
	#define TX_SYS5_FIFO_CONFIG_AFE_FIFO_CHANNEL0_ENABLE		BIT(0)

#define TX_SYS5_FIFO_SAMP01_CFG						0x00E9
#define TX_SYS5_FIFO_SAMP23_CFG						0x00EA
#define TX_SYS5_CONNECT_FIFO_CFG					0x00EB
#define TX_SYS5_IO_CALIB_CONTROL					0x00EC
#define TX_SYS5_SSTL_BIDIR_OUT						0x00ED
#define TX_SYS5_SSTL_OUT						0x00EE
#define TX_SYS5_SSTL_DIFF_OUT						0x00EF

// HDCP shadow register
#define TX_HDCP_SHW_BKSV_0						0x0100
#define TX_HDCP_SHW_BKSV_1						0x0101
#define TX_HDCP_SHW_BKSV_2						0x0102
#define TX_HDCP_SHW_BKSV_3						0x0103
#define TX_HDCP_SHW_BKSV_4						0x0104
#define TX_HDCP_SHW_RI1_0						0x0108
#define TX_HDCP_SHW_RI1_1						0x0109
#define TX_HDCP_SHW_PJ1							0x010A
#define TX_HDCP_SHW_AKSV_0						0x0110
#define TX_HDCP_SHW_AKSV_1						0x0111
#define TX_HDCP_SHW_AKSV_2						0x0112
#define TX_HDCP_SHW_AKSV_3						0x0113
#define TX_HDCP_SHW_AKSV_4						0x0114
#define TX_HDCP_SHW_AINFO						0x0115
#define TX_HDCP_SHW_AN_0						0x0118
#define TX_HDCP_SHW_AN_1						0x0119
#define TX_HDCP_SHW_AN_2						0x011A
#define TX_HDCP_SHW_AN_3						0x011B
#define TX_HDCP_SHW_AN_4						0x011C
#define TX_HDCP_SHW_AN_5						0x011D
#define TX_HDCP_SHW_AN_6						0x011E
#define TX_HDCP_SHW_AN_7						0x011F
#define TX_HDCP_SHW_V1_H0_0						0x0120
#define TX_HDCP_SHW_V1_H0_1						0x0121
#define TX_HDCP_SHW_V1_H0_2						0x0122
#define TX_HDCP_SHW_V1_H0_3						0x0123
#define TX_HDCP_SHW_V1_H1_0						0x0124
#define TX_HDCP_SHW_V1_H1_1						0x0125
#define TX_HDCP_SHW_V1_H1_2						0x0126
#define TX_HDCP_SHW_V1_H1_3						0x0127
#define TX_HDCP_SHW_V1_H2_0						0x0128
#define TX_HDCP_SHW_V1_H2_1						0x0129
#define TX_HDCP_SHW_V1_H2_2						0x012A
#define TX_HDCP_SHW_V1_H2_3						0x012B
#define TX_HDCP_SHW_V1_H3_0						0x012C
#define TX_HDCP_SHW_V1_H3_1						0x012D
#define TX_HDCP_SHW_V1_H3_2						0x012E
#define TX_HDCP_SHW_V1_H3_3						0x012F
#define TX_HDCP_SHW_V1_H4_0						0x0130
#define TX_HDCP_SHW_V1_H4_1						0x0131
#define TX_HDCP_SHW_V1_H4_2						0x0132
#define TX_HDCP_SHW_V1_H4_3						0x0133
#define TX_HDCP_SHW_BCAPS						0x0140
#define TX_HDCP_SHW_BSTATUS_0						0x0141
#define TX_HDCP_SHW_BSTATUS_1						0x0142
#define TX_HDCP_SHW_KSV_FIFO						0x0143

// system status 0
#define TX_SYSST0_CONNECT_FIFO						0x0180
#define TX_SYSST0_PLL_MONITOR						0x0181
#define TX_SYSST0_AFE_FIFO						0x0182
#define TX_SYSST0_ROM_STATUS						0x018F

// hdcp status
#define TX_HDCP_ST_AUTHENTICATION					0x0190
#define TX_HDCP_ST_FRAME_COUNT						0x0191
#define TX_HDCP_ST_STATUS_0						0x0192
#define TX_HDCP_ST_STATUS_1						0x0193
#define TX_HDCP_ST_STATUS_2						0x0194
#define TX_HDCP_ST_STATUS_3						0x0195
#define TX_HDCP_ST_EDID_STATUS						0x0196
	#define TX_HDCP_ST_EDID_STATUS_SYSTEM_STATUS		GENMASK(7, 6)
	#define TX_HDCP_ST_EDID_STATUS_SYSTEM_STATUS_NO_SINK_ATTACHED	0x0
	#define TX_HDCP_ST_EDID_STATUS_SYSTEM_STATUS_READING_EDID	0x1
	#define TX_HDCP_ST_EDID_STATUS_SYSTEM_STATUS_DVI_MODE		0x2
	#define TX_HDCP_ST_EDID_STATUS_SYSTEM_STATUS_HDMI_MODE		0x3
	#define TX_HDCP_ST_EDID_STATUS_EDID_DATA_READY			BIT(4)
	#define TX_HDCP_ST_EDID_STATUS_HPD_STATUS			BIT(1)

#define TX_HDCP_ST_MEM_STATUS						0x0197
#define TX_HDCP_ST_ST_MODE						0x019F

// video status
#define TX_VIDEO_ST_ACTIVE_PIXELS_1					0x01A0
#define TX_VIDEO_ST_ACTIVE_PIXELS_2					0x01A1
#define TX_VIDEO_ST_FRONT_PIXELS					0x01A2
#define TX_VIDEO_ST_HSYNC_PIXELS					0x01A3
#define TX_VIDEO_ST_BACK_PIXELS						0x01A4
#define TX_VIDEO_ST_ACTIVE_LINES_1					0x01A5
#define TX_VIDEO_ST_ACTIVE_LINES_2					0x01A6
#define TX_VIDEO_ST_EOF_LINES						0x01A7
#define TX_VIDEO_ST_VSYNC_LINES						0x01A8
#define TX_VIDEO_ST_SOF_LINES						0x01A9
#define TX_VIDEO_ST_DTV_TIMING						0x01AA
#define TX_VIDEO_ST_DTV_MODE						0x01AB
// audio status
#define TX_VIDEO_ST_AUDIO_STATUS					0x01AC
#define TX_AFE_STATUS_0							0x01AE
#define TX_AFE_STATUS_1							0x01AF

#define TX_IEC60958_ST_SUB1_OFFSET					0x01B0
#define TX_IEC60958_ST_SUB2_OFFSET					0x01C8

// system status 1
#define TX_SYSST1_CALIB_BIT_RESULT_0					0x01E0
#define TX_SYSST1_CALIB_BIT_RESULT_1					0x01E1
//HDMI_STATUS_OUT[7:0]
#define TX_HDMI_PHY_READBACK_0						0x01E2
//HDMI_COMP_OUT[4]
//HDMI_STATUS_OUT[11:8]
#define TX_HDMI_PHY_READBACK_1						0x01E3
#define TX_SYSST1_CALIB_BIT_RESULT_4					0x01E4
#define TX_SYSST1_CALIB_BIT_RESULT_5					0x01E5
#define TX_SYSST1_CALIB_BIT_RESULT_6					0x01E6
#define TX_SYSST1_CALIB_BIT_RESULT_7					0x01E7
#define TX_SYSST1_CALIB_BUS_RESULT_0					0x01E8
#define TX_SYSST1_CALIB_BUS_RESULT_1					0x01E9
#define TX_SYSST1_CALIB_BUS_RESULT_2					0x01EA
#define TX_SYSST1_CALIB_BUS_RESULT_3					0x01EB
#define TX_SYSST1_CALIB_BUS_RESULT_4					0x01EC
#define TX_SYSST1_CALIB_BUS_RESULT_5					0x01ED
#define TX_SYSST1_CALIB_BUS_RESULT_6					0x01EE
#define TX_SYSST1_CALIB_BUS_RESULT_7					0x01EF

// Packet status
#define TX_PACKET_ST_REQUEST_STATUS_1					0x01F0
#define TX_PACKET_ST_REQUEST_STATUS_2					0x01F1
#define TX_PACKET_ST_REQUEST_MISSED_1					0x01F2
#define TX_PACKET_ST_REQUEST_MISSED_2					0x01F3
#define TX_PACKET_ST_ENCODE_STATUS_0					0x01F4
#define TX_PACKET_ST_ENCODE_STATUS_1					0x01F5
#define TX_PACKET_ST_ENCODE_STATUS_2					0x01F6
#define TX_PACKET_ST_TIMER_STATUS					0x01F7

// tmds status
#define TX_TMDS_ST_CLOCK_METER_1					0x01F8
#define TX_TMDS_ST_CLOCK_METER_2					0x01F9
#define TX_TMDS_ST_CLOCK_METER_3					0x01FA
#define TX_TMDS_ST_TMDS_STATUS_1					0x01FC
#define TX_TMDS_ST_TMDS_STATUS_2					0x01FD
#define TX_TMDS_ST_TMDS_STATUS_3					0x01FE
#define TX_TMDS_ST_TMDS_STATUS_4					0x01FF


// Packet register
#define TX_PKT_REG_SPD_INFO_BASE_ADDR					0x0200
#define TX_PKT_REG_VEND_INFO_BASE_ADDR					0x0220
#define TX_PKT_REG_MPEG_INFO_BASE_ADDR					0x0240
#define TX_PKT_REG_AVI_INFO_BASE_ADDR					0x0260
#define TX_PKT_REG_AUDIO_INFO_BASE_ADDR					0x0280
#define TX_PKT_REG_ACP_INFO_BASE_ADDR					0x02A0
#define TX_PKT_REG_ISRC1_BASE_ADDR					0x02C0
#define TX_PKT_REG_ISRC2_BASE_ADDR					0x02E0
#define TX_PKT_REG_EXCEPT0_BASE_ADDR					0x0300
#define TX_PKT_REG_EXCEPT1_BASE_ADDR					0x0320
#define TX_PKT_REG_EXCEPT2_BASE_ADDR					0x0340
#define TX_PKT_REG_EXCEPT3_BASE_ADDR					0x0360
#define TX_PKT_REG_EXCEPT4_BASE_ADDR					0x0380
#define TX_PKT_REG_GAMUT_P0_BASE_ADDR					0x03A0
#define TX_PKT_REG_GAMUT_P1_1_BASE_ADDR					0x03C0
#define TX_PKT_REG_GAMUT_P1_2_BASE_ADDR					0x03E0

#define TX_RX_EDID_OFFSET						0x0600

/* HDMI OTHER registers */

#define HDMI_OTHER_CTRL0						0x8000
#define HDMI_OTHER_CTRL1						0x8001
	#define HDMI_OTHER_CTRL1_POWER_ON				BIT(15)
	#define HDMI_OTHER_CTRL1_HDMI_AUDIO_CLOCK_ON			BIT(13)

#define HDMI_OTHER_STATUS0						0x8002
#define HDMI_OTHER_CTRL2						0x8003
#define HDMI_OTHER_INTR_MASKN						0x8004
	#define HDMI_OTHER_INTR_MASKN_TX_EDID_INT_RISE			BIT(2)
	#define HDMI_OTHER_INTR_MASKN_TX_HPD_INT_FALL			BIT(1)
	#define HDMI_OTHER_INTR_MASKN_TX_HPD_INT_RISE			BIT(0)

#define HDMI_OTHER_INTR_STAT						0x8005
	#define HDMI_OTHER_INTR_STAT_EDID_RISING			BIT(2)
	#define HDMI_OTHER_INTR_STAT_HPD_FALLING			BIT(1)
	#define HDMI_OTHER_INTR_STAT_HPD_RISING				BIT(0)

#define HDMI_OTHER_INTR_STAT_CLR					0x8006
	#define HDMI_OTHER_INTR_STAT_CLR_EDID_RISING			BIT(2)
	#define HDMI_OTHER_INTR_STAT_CLR_HPD_FALLING			BIT(1)
	#define HDMI_OTHER_INTR_STAT_CLR_HPD_RISING			BIT(0)

#define HDMI_OTHER_AVI_INTR_MASKN0					0x8008
#define HDMI_OTHER_AVI_INTR_MASKN1					0x8009
#define HDMI_OTHER_RX_AINFO_INTR_MASKN0					0x800a
#define HDMI_OTHER_RX_AINFO_INTR_MASKN1					0x800b
#define HDMI_OTHER_RX_PACKET_INTR_CLR					0x800c

#endif /* __TXCCQ_TXC_84352_H__ */
