obj-y = clk.o

obj-$(CONFIG_SOC_TYPE_FALCON) += \
	clk-falcon.o

obj-$(CONFIG_SOC_TYPE_XWAY) += \
	clk-amazonse.o \
	clk-arx100.o \
	clk-arx300.o \
	clk-danube.o \
	clk-grx390.o \
	clk-vrx200.o \
	clk-xway-cgu.o \
	clk-xway-compat.o \
	clk-xway-pmu.o
