obj-$(CONFIG_SOC_TYPE_FALCON) += \
	clk-falcon.o

obj-$(CONFIG_SOC_TYPE_XWAY) += \
	clk-amazonse.o \
	clk-arx300.o \
	clk-danube.o \
	clk-grx300.o \
	clk-xrx100.o \
	clk-xrx200.o \
	clk-xway-cgu.o \
	clk-xway-compat.o \
	clk-xway-pmu.o
